=== Veriteworks/magento2-l10n/app/code/Magento/ZipCodeConverter/etc/zipconverter.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * This schema must be used to validate zipconverter.xml files
 *
 * Copyright Â© Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config" type="configType">
    </xs:element>

    <xs:complexType name="converterType">
        <xs:sequence>
            <xs:element name="gateway" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="country" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="zip" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="city" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="street_1" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="street_2" type="xs:string" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="countryCode"/>
    </xs:complexType>

    <xs:complexType name="configType">
        <xs:sequence>
            <xs:element type="converterType" name="zip" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== Veriteworks/magento2-l10n/app/code/Magento/ZipCodeConverter/etc/zipconverter.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
/**
 * Copyright Â© Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_ZipCodeConverter:etc/zipconverter.xsd">
    <converter countryCode="default">
        <gateway>https://example.com/path/to/api</gateway>
        <country>#country</country>
        <zip>#zip</zip>
        <city>#city</city>
        <street_1>#street_1</street_1>
        <street_2>#street_2</street_2>
    </converter>
    <converter countryCode="US">
        <gateway>https://example.com/path/to/api</gateway>
        <country>#country</country>
        <zip>#zip</zip>
        <city>#city</city>
        <street_1>#street_1</street_1>
        <street_2>#street_2</street_2>
    </converter>
    <converter countryCode  ="JP">
        <gateway>https://example.com/path/to/api</gateway>
        <country>#country</country>
        <zip>#zip</zip>
        <city>#city</city>
        <street_1>#street_1</street_1>
        <street_2>#street_2</street_2>
    </converter>
</config>
